language: csharp
solution: Katsuben.sln

dotnet: 3.1
mono: none

install:
  - dotnet restore

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - dotnet build
  - dotnet test TestKatsuben/TestKatsuben.csproj --collect:"XPlat Code Coverage"

after_script:
  - cp $(find . -iname coverage.cobertura.xml) cobertura.xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
